lb:
  image: rancher/lb-service-haproxy:v0.6.2
  ports:
  - 8086:8086/tcp
  labels:
    io.rancher.container.agent.role: environmentAdmin
    io.rancher.container.create_agent: 'true'
influxdb:
  image: influxdb:1.2.2-alpine
  stdin_open: true
  tty: true
  volumes_from:
  - influxdb-volume
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: influxdb-volume
    io.rancher.container.hostname_override: container_name
influxdb-volume:
  image: rawmind/alpine-volume:0.0.2-1
  environment:
    SERVICE_GID: '0'
    SERVICE_UID: '0'
    SERVICE_VOLUME: /var/lib/influxdb
  net: none
  volumes:
  - /opt/iosa_deploy/influxdb/data:/var/lib/influxdb
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
