.catalog:
  name: "Influxdb"
  version: "1.2.2-rancher1"
  description: "FLEX-STREAM Influxdb"
  questions:
    - variable: "influxdb_scale"
      description: "The number of influxdb instance in rancher ."
      label: "Add Inlfuxdb Host Number"
      required: true
      default: 1
      type: "int"
    - variable: "expose_port"
      description: "port to export, default 8086."
      label: "influxdb expose port"
      required: true
      default: "8086"
      type: "string"
    - variable: "data_dir"
      description: "data dir on host, default /opt/iosa_deploy/influxdb/data"
      label: "data dir on host"
      required: true
      default: "/opt/iosa_deploy/influxdb/data"
      type: "string"


influxdb:
  scale: ${influxdb_scale}
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 8086
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate

influxdb-volume:
    scale: 1
    start_on_create: true

lb:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - hostname: 172.16.54.136
      path: /
      priority: 1
      protocol: http
      service: influxdb
      source_port: 8086
      target_port: 8086
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
