
mysql:
  image: docker-registry:6000/iosa/mysql:v5.7.18
  mem_limit: ${MySQL_MEM_LIMIT}000000
  tty: true
  stdin_open: true
  privileged: true

  volumes:
  - ${INIT_DB_SCRIPTS}:/docker-entrypoint-initdb.d
  - ${CONFIG_FILE}:/etc/my.cnf
  - ${DATA_DIR}:${DATA_DIR}
  
  labels:
    io.certus.iosa.mysql.service.name: mysql
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: db_136=db_136
   
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    DATA_DIR: ${DATA_DIR}
    CONFIG_FILE: ${CONFIG_FILE}
    CONN_PORT: ${CONN_PORT}
    CHARACTER_SET_SERVER: ${CHARACTER_SET_SERVER}
    COLLATION_SERVER: ${COLLATION_SERVER}
    MYSQL_ARGS: --datadir=${DATA_DIR} --character-set-server=${CHARACTER_SET_SERVER} --collation-server=${COLLATION_SERVER}
   
  ports:
  - ${CONN_PORT}:13306

  command: mysqld ${MYSQL_ARGS}
  entrypoint: /entrypoint.sh
 
 
