.catalog:
  name: "Kettle"
  version: "pdi-ce-5.3.0.0-213"
  description: "FLEX-STREAM Kettle"
  questions:
    - variable: "Kettle_JVM_Xms"
      description: "jvm Xms, default 1024m."
      label: "Jboss Jvm Xms(mb)"
      required: true
      default: 1024
      type: "int"
    - variable: "Kettle_JVM_Xmx"
      description: "jvm Xmx, default 1024m."
      label: "Kettle Jvm Xmx(mb)"
      required: true
      default: 2048
      type: "int"
    - variable: "Kettle_jvm_XX_MaxPermSize"
      description: "jvm Xmx, default 512m."
      label: "Kettle Jvm MaxPermSize(mb)"
      required: true
      default: 1024
      type: "int"
    - variable: "mysql_link"
      description: "Choose the MySQL service to use."
      label: "MySQL stack/service"
      default: "mysql/mysql"
      required: false
      type: "service"
    - variable: "influxdb_link"
      description: "Choose the InfluxDB service to use."
      label: "InfluxDB stack/service"
      default: "influxdb/influxdb"
      required: false
      type: "service"

kettle:
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
  


  

